# Generated by Django 2.2.3 on 2019-07-30 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DialogUser',
            fields=[
                ('uid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('time_enrolled', models.DateTimeField(null=True)),
                ('photo', models.BinaryField(null=True)),
                ('vector', models.BinaryField(null=True)),
            ],
        ),
    ]
